### ISSUE TITLE
facet_ncol parameter not used

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubVis#12]
`facet_nrow` seems to be passed on to `output_plot` [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubVis/blob/07aa2c333a982002137ed5ae639d96cb1eb42cac/R/plot_step_ahead_model_output.R#L870), but not `facet_ncol`

**Comment by LucieContamin** [comment]
Thank you for noticing!

Fixed in the commit [7d30cc8](https://github.com/Infectious-Disease-Modeling-Hubs/hubVis/pull/2/commits/7d30cc82d93e49abff94adbae47ffadfad44b5f3).
I also update the vignette with an example using this parameter.
