### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubVis#15]
Use definition below
[Definitions of roles](https://r-pkgs.org/description.html#sec-description-authors-at-r) (Author, maintainer, contributor, etc…)

Going forward, ensure that PRs from new contributors include an update to authorship roles (for R packages, in description file)

**Comment by LucieContamin** [comment]
Done in [55a8228](https://github.com/Infectious-Disease-Modeling-Hubs/hubVis/commit/55a822859c4cb4a26a79266ff07e7a120661ac07)
