### ISSUE TITLE
interactive vis does not respect the `group` argument

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubVis#32]
Working with data from `hubExamples`, the following code produces a static plot that looks as expected:

```
library(dplyr)
library(hubExamples)
library(hubVis)

plot_step_ahead_model_output(
    model_output_data = forecast_outputs |> filter(output_type %in% c("quantile", "median")),
    target_data = forecast_target_ts |>
        filter(location %in% c("25", "48"),
               date >= "2022-10-01", date <= "2023-04-01"),
    use_median_as_point = TRUE,
    x_col_name = "target_end_date",
    intervals = c(0.5, 0.8, 0.9),
    facet = "location",
    group = "reference_date",
   interactive = FALSE
)
```

![image](https://github.com/Infectious-Disease-Modeling-Hubs/hubVis/assets/5132208/44abc3bb-6e83-421a-81a4-5bfdfdd2c895)

However, if we set `interactive = TRUE`, forecasts from different reference dates are connected:
```
plot_step_ahead_model_output(
    model_output_data = forecast_outputs |> filter(output_type %in% c("quantile", "median")),
    target_data = forecast_target_ts |>
        filter(location %in% c("25", "48"),
               date >= "2022-10-01", date <= "2023-04-01"),
    use_median_as_point = TRUE,
    x_col_name = "target_end_date",
    intervals = c(0.5, 0.8, 0.9),
    facet = "location",
    group = "reference_date",
   interactive = TRUE
)
```

<img width="1764" alt="Screenshot 2024-04-25 at 4 43 12 PM" src="https://github.com/Infectious-Disease-Modeling-Hubs/hubVis/assets/5132208/42936e09-3eb7-4ac1-a1ee-20b928497054">

**Comment by LucieContamin** [comment]
It's an ongoing issue (see #16). The `group` parameter documentation should say that it is only currently available for "static" plot. I can make it more visible, but as it's a temporary issue I was not sure it was necessary.

**Comment by elray1** [comment]
Thanks, i didn't realize that this was already covered in that other issue.  I'll close this issue as a duplicate of that one.
